---
title: Economic Research Foundation
author: erf
email: shreya@erfindia.in
description: 'ERF conducts research in the field of economics and social issues, public policy, international economic affairs.'
baseurl: ''
url: http://erfindia.in
lang: en
color_scheme: github
github_username: erfindia
twitter_username: DevEconNetwork
facebook-official_username: DevEconNetwork

#build settings
# theme: jekyll-theme-kagami
permalink: pretty

exclude:
- Gemfile
- Gemfile.lock
- vendor/bundle

plugins:
  - jekyll-sitemap
