---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections:
- path: ''
  label: Pages
  create: all
- path: _posts
  label: Posts
  create: all
upload_dir: media
public_path: "/media"
front_matter_path: "/media"
use_front_matter_path: false
file_template: ":filename:"
